services:
  yolox-backend:
    image: yolox-backend:0.0.1-SNAPSHOT
    container_name: yolox-backend
    hostname: yolox-backend
    environment:
      - LOCAL_STORAGE_PATH=/data-files
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB_DATABASE=yolox-boilerplate
      - DEBUG=true
    ports:
      - "8000:8000"
    volumes:
      - ./integration/data-files/:/data-files
      - ./integration/tmp:/tmp
      - ./backend/app:/app

  yolox-frontend:
    image: yolox-frontend:0.0.1-SNAPSHOT-REACT
    container_name: yolox-frontend
    hostname: yolox-frontend
    environment:
      - API_URL=yolox-backend:8000
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: npm start

  mongo:
    image: arm64v8/mongo
    # image: amd64/mongo
    container_name: mongo
    hostname: mongo
    volumes:
      - ./integration/mongodb/data:/data/db
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MONGODB_ENABLE_DIRECTORY_PER_DB=yes
    ports:
      - "27017:27017"
    restart: always
